"""Delete cascade.

Revision ID: 52c85a60d7ec
Revises: f7b6c2a023c8
Create Date: 2023-06-14 20:39:01.053635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52c85a60d7ec'
down_revision = 'f7b6c2a023c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=mysql.YEAR(display_width=4),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.DateTime(),
               type_=mysql.YEAR(display_width=4),
               existing_nullable=False)

    # ### end Alembic commands ###
