"""Small changes.

Revision ID: 9318c0c9c160
Revises: 52c85a60d7ec
Create Date: 2023-06-14 20:44:59.399776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9318c0c9c160'
down_revision = '52c85a60d7ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.String(length=4),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
