"""Small changes.

Revision ID: f7b6c2a023c8
Revises: 58d921c621fb
Create Date: 2023-06-13 17:17:18.421639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b6c2a023c8'
down_revision = '58d921c621fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_sum', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rating_num', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('rating_num')
        batch_op.drop_column('rating_sum')

    # ### end Alembic commands ###
